import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const RUNTIME_BASHRC_TEMPLATE_PATH = "templates/runtime_bashrc.j2";

function resolveTemplatePath(): string {
  const distRelativePath = join(__dirname, "..", RUNTIME_BASHRC_TEMPLATE_PATH);
  if (existsSync(distRelativePath)) {
    return distRelativePath;
  }

  const sourceRelativePath = join(__dirname, "..", "..", "src", RUNTIME_BASHRC_TEMPLATE_PATH);
  if (existsSync(sourceRelativePath)) {
    return sourceRelativePath;
  }

  throw new Error(`Runtime bashrc template was not found at ${distRelativePath} or ${sourceRelativePath}`);
}

function renderJinjaTemplate(template: string, context: Record<string, string>): string {
  return template.replace(/{{\s*([a-zA-Z0-9_]+)\s*}}/g, (_match, key: string) => {
    const value = context[key];
    if (value === undefined) {
      throw new Error(`Missing template value for key '${key}'`);
    }
    return value;
  });
}

export function renderRuntimeBashrc(homeDirectory: string): string {
  const fallbackTemplate = `# CompanyHelm runtime shell initialization.
# This file is generated by companyhelm-runner when a thread runtime starts.

if [ -z "\${NVM_DIR:-}" ] || [ ! -s "$NVM_DIR/nvm.sh" ]; then
  for candidate in "/usr/local/nvm" "$HOME/.nvm" "/opt/nvm" "/root/.nvm"; do
    if [ -s "$candidate/nvm.sh" ]; then
      export NVM_DIR="$candidate"
      break
    fi
  done
fi

if [ -n "\${NVM_DIR:-}" ] && [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
  nvm use --silent default >/dev/null 2>&1 || true
  if [ -s "$NVM_DIR/bash_completion" ]; then
    . "$NVM_DIR/bash_completion"
  fi
fi
`;

  try {
    const template = readFileSync(resolveTemplatePath(), "utf8");
    return renderJinjaTemplate(template, {
      home_directory: homeDirectory,
    }).trimEnd() + "\n";
  } catch {
    return fallbackTemplate.trimEnd() + "\n";
  }
}
